export interface EmojiEntry {
  emoji: string;
  keywords: string[];
}

export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys',
    icon: '😀',
    emojis: [
      { emoji: '😀', keywords: ['grinning', 'smile', 'happy', 'face'] },
      { emoji: '😃', keywords: ['smiley', 'smile', 'happy', 'open mouth'] },
      { emoji: '😄', keywords: ['smile', 'happy', 'grin', 'eyes'] },
      { emoji: '😁', keywords: ['grin', 'smile', 'beaming', 'happy'] },
      { emoji: '😆', keywords: ['laughing', 'haha', 'lol', 'squint'] },
      { emoji: '😅', keywords: ['sweat smile', 'nervous', 'relief', 'phew'] },
      { emoji: '🤣', keywords: ['rofl', 'rolling', 'laughing', 'lmao', 'floor'] },
      { emoji: '😂', keywords: ['joy', 'laugh', 'cry', 'tears', 'lol', 'haha'] },
      { emoji: '🙂', keywords: ['slightly smiling', 'smile', 'ok', 'fine'] },
      { emoji: '😉', keywords: ['wink', 'flirt', 'smirk'] },
      { emoji: '😊', keywords: ['blush', 'smile', 'happy', 'shy', 'warm'] },
      { emoji: '😇', keywords: ['angel', 'innocent', 'halo', 'blessed'] },
      { emoji: '🥰', keywords: ['love', 'hearts', 'adore', 'smiling', 'affection'] },
      { emoji: '😍', keywords: ['heart eyes', 'love', 'crush', 'adore'] },
      { emoji: '🤩', keywords: ['star struck', 'excited', 'stars', 'amazing', 'wow'] },
      { emoji: '😘', keywords: ['kiss', 'blowing kiss', 'love', 'smooch'] },
      { emoji: '😋', keywords: ['yummy', 'delicious', 'tongue', 'food', 'tasty'] },
      { emoji: '😛', keywords: ['tongue', 'silly', 'playful'] },
      { emoji: '😜', keywords: ['wink tongue', 'silly', 'crazy', 'joking'] },
      { emoji: '🤪', keywords: ['zany', 'crazy', 'wild', 'goofy', 'silly'] },
      { emoji: '😝', keywords: ['tongue closed eyes', 'silly', 'bleh'] },
      { emoji: '🤑', keywords: ['money', 'rich', 'dollar', 'cash'] },
      { emoji: '🤗', keywords: ['hug', 'hugging', 'warm', 'open arms'] },
      { emoji: '🤭', keywords: ['giggle', 'oops', 'covering mouth', 'tee hee'] },
      { emoji: '🤫', keywords: ['shush', 'quiet', 'secret', 'shh', 'silence'] },
      { emoji: '🤔', keywords: ['thinking', 'hmm', 'wondering', 'curious'] },
      { emoji: '🤐', keywords: ['zipper mouth', 'secret', 'mute', 'zip'] },
      { emoji: '🤨', keywords: ['raised eyebrow', 'skeptical', 'sus', 'doubt'] },
      { emoji: '😐', keywords: ['neutral', 'meh', 'straight face', 'blank'] },
      { emoji: '😑', keywords: ['expressionless', 'blank', 'unamused', 'flat'] },
      { emoji: '😶', keywords: ['no mouth', 'speechless', 'silence', 'mute'] },
      { emoji: '😏', keywords: ['smirk', 'sly', 'suggestive', 'flirt'] },
      { emoji: '😒', keywords: ['unamused', 'annoyed', 'bored', 'meh'] },
      { emoji: '🙄', keywords: ['eye roll', 'annoyed', 'whatever', 'duh'] },
      { emoji: '😬', keywords: ['grimace', 'awkward', 'yikes', 'cringe'] },
      { emoji: '😮‍💨', keywords: ['exhale', 'sigh', 'relief', 'tired'] },
      { emoji: '🤥', keywords: ['liar', 'pinocchio', 'lying', 'nose'] },
      { emoji: '😌', keywords: ['relieved', 'peaceful', 'calm', 'zen'] },
      { emoji: '😔', keywords: ['sad', 'pensive', 'disappointed', 'down'] },
      { emoji: '😪', keywords: ['sleepy', 'tired', 'snot bubble'] },
      { emoji: '🤤', keywords: ['drool', 'drooling', 'hungry', 'yum'] },
      { emoji: '😴', keywords: ['sleeping', 'zzz', 'tired', 'nap', 'snore'] },
      { emoji: '😷', keywords: ['mask', 'sick', 'covid', 'flu', 'ill'] },
      { emoji: '🤒', keywords: ['sick', 'thermometer', 'fever', 'ill'] },
      { emoji: '🤕', keywords: ['hurt', 'injured', 'bandage', 'head'] },
      { emoji: '🤢', keywords: ['nauseous', 'sick', 'green', 'gross'] },
      { emoji: '🤮', keywords: ['vomit', 'puke', 'sick', 'throw up', 'gross'] },
      { emoji: '🥵', keywords: ['hot', 'sweating', 'heat', 'warm', 'spicy'] },
      { emoji: '🥶', keywords: ['cold', 'freezing', 'frozen', 'ice', 'brr'] },
      { emoji: '🥴', keywords: ['woozy', 'drunk', 'dizzy', 'tipsy'] },
      { emoji: '😵', keywords: ['dizzy', 'unconscious', 'dead', 'knocked out'] },
      { emoji: '🤯', keywords: ['mind blown', 'exploding head', 'shocked', 'wow'] },
      { emoji: '🤠', keywords: ['cowboy', 'hat', 'western', 'yeehaw'] },
      { emoji: '🥳', keywords: ['party', 'celebrate', 'birthday', 'confetti'] },
      { emoji: '🥸', keywords: ['disguise', 'glasses', 'mustache', 'incognito'] },
      { emoji: '😎', keywords: ['cool', 'sunglasses', 'awesome', 'swag'] },
      { emoji: '🤓', keywords: ['nerd', 'glasses', 'smart', 'geek'] },
      { emoji: '🧐', keywords: ['monocle', 'fancy', 'inspect', 'hmm'] },
      { emoji: '😕', keywords: ['confused', 'puzzled', 'unsure'] },
      { emoji: '😟', keywords: ['worried', 'concerned', 'anxious'] },
      { emoji: '🙁', keywords: ['frown', 'sad', 'slightly frowning', 'unhappy'] },
      { emoji: '😮', keywords: ['open mouth', 'surprised', 'oh', 'wow'] },
      { emoji: '😯', keywords: ['hushed', 'surprised', 'quiet'] },
      { emoji: '😲', keywords: ['astonished', 'shocked', 'wow', 'omg'] },
      { emoji: '😳', keywords: ['flushed', 'embarrassed', 'shocked', 'red'] },
      { emoji: '🥺', keywords: ['pleading', 'puppy eyes', 'please', 'begging', 'uwu'] },
      { emoji: '😦', keywords: ['frowning', 'open mouth', 'uh oh'] },
      { emoji: '😧', keywords: ['anguished', 'distressed', 'oh no'] },
      { emoji: '😨', keywords: ['fearful', 'scared', 'afraid', 'panic'] },
      { emoji: '😰', keywords: ['anxious', 'nervous', 'sweat', 'worried'] },
      { emoji: '😥', keywords: ['sad', 'relieved', 'disappointed', 'tear'] },
      { emoji: '😢', keywords: ['cry', 'sad', 'tear', 'upset'] },
      { emoji: '😭', keywords: ['sob', 'crying', 'loud cry', 'bawling', 'tears'] },
      { emoji: '😱', keywords: ['scream', 'horror', 'scared', 'omg', 'shocked'] },
      { emoji: '😖', keywords: ['confounded', 'frustrated', 'ugh'] },
      { emoji: '😣', keywords: ['persevere', 'struggling', 'endure'] },
      { emoji: '😞', keywords: ['disappointed', 'sad', 'let down'] },
      { emoji: '😓', keywords: ['sweat', 'hard work', 'tired', 'downcast'] },
      { emoji: '😩', keywords: ['weary', 'tired', 'exhausted', 'over it'] },
      { emoji: '😫', keywords: ['tired', 'exhausted', 'fed up'] },
      { emoji: '🥱', keywords: ['yawn', 'bored', 'sleepy', 'tired'] },
      { emoji: '😤', keywords: ['angry', 'huffing', 'frustrated', 'steam', 'triumph'] },
      { emoji: '😡', keywords: ['angry', 'mad', 'rage', 'furious', 'pouting'] },
      { emoji: '😠', keywords: ['angry', 'mad', 'annoyed', 'grumpy'] },
      { emoji: '🤬', keywords: ['swearing', 'cursing', 'angry', 'symbols'] },
      { emoji: '😈', keywords: ['devil', 'evil', 'smiling', 'imp', 'mischief'] },
      { emoji: '👿', keywords: ['angry devil', 'evil', 'imp'] },
      { emoji: '💀', keywords: ['skull', 'dead', 'death', 'skeleton', 'rip'] },
      { emoji: '💩', keywords: ['poop', 'poo', 'crap', 'shit'] },
      { emoji: '🤡', keywords: ['clown', 'silly', 'joke', 'circus'] },
      { emoji: '👻', keywords: ['ghost', 'halloween', 'boo', 'spooky'] },
      { emoji: '👽', keywords: ['alien', 'ufo', 'space', 'extraterrestrial'] },
      { emoji: '🤖', keywords: ['robot', 'bot', 'machine', 'android'] },
    ],
  },
  {
    name: 'Gestures',
    icon: '👋',
    emojis: [
      { emoji: '👋', keywords: ['wave', 'hello', 'hi', 'bye', 'goodbye'] },
      { emoji: '🤚', keywords: ['raised back of hand', 'stop', 'backhand'] },
      { emoji: '🖐', keywords: ['hand', 'fingers', 'five', 'high five', 'splayed'] },
      { emoji: '✋', keywords: ['hand', 'stop', 'high five', 'raised'] },
      { emoji: '🖖', keywords: ['vulcan', 'spock', 'star trek', 'live long'] },
      { emoji: '👌', keywords: ['ok', 'perfect', 'fine', 'nice', 'pinch'] },
      { emoji: '🤌', keywords: ['pinched fingers', 'italian', 'chef kiss', 'perfecto'] },
      { emoji: '🤏', keywords: ['pinching', 'small', 'tiny', 'little bit'] },
      { emoji: '✌', keywords: ['peace', 'victory', 'two', 'v sign'] },
      { emoji: '🤞', keywords: ['crossed fingers', 'luck', 'hope', 'wish'] },
      { emoji: '🤟', keywords: ['love you', 'rock on', 'ily'] },
      { emoji: '🤘', keywords: ['rock', 'metal', 'horns', 'devil horns'] },
      { emoji: '🤙', keywords: ['call me', 'shaka', 'hang loose', 'phone'] },
      { emoji: '👈', keywords: ['point left', 'left', 'this', 'direction'] },
      { emoji: '👉', keywords: ['point right', 'right', 'this', 'direction'] },
      { emoji: '👆', keywords: ['point up', 'up', 'above'] },
      { emoji: '👇', keywords: ['point down', 'down', 'below'] },
      { emoji: '☝', keywords: ['point up', 'one', 'index', 'actually'] },
      { emoji: '👍', keywords: ['thumbs up', 'yes', 'good', 'like', 'approve', '+1'] },
      { emoji: '👎', keywords: ['thumbs down', 'no', 'bad', 'dislike', '-1'] },
      { emoji: '✊', keywords: ['fist', 'power', 'punch', 'solidarity'] },
      { emoji: '👊', keywords: ['fist bump', 'punch', 'bro', 'bump'] },
      { emoji: '🤛', keywords: ['left fist', 'fist bump', 'punch'] },
      { emoji: '🤜', keywords: ['right fist', 'fist bump', 'punch'] },
      { emoji: '👏', keywords: ['clap', 'applause', 'bravo', 'congrats'] },
      { emoji: '🙌', keywords: ['raised hands', 'celebrate', 'hooray', 'praise'] },
      { emoji: '👐', keywords: ['open hands', 'jazz hands'] },
      { emoji: '🤲', keywords: ['palms up', 'prayer', 'cupped hands'] },
      { emoji: '🤝', keywords: ['handshake', 'deal', 'agree', 'partnership'] },
      { emoji: '🙏', keywords: ['pray', 'please', 'thank you', 'thanks', 'hope', 'namaste'] },
      { emoji: '💪', keywords: ['muscle', 'strong', 'flex', 'bicep', 'strength'] },
      { emoji: '🦾', keywords: ['mechanical arm', 'robot', 'prosthetic', 'strong'] },
      { emoji: '🫶', keywords: ['heart hands', 'love', 'care', 'hands heart'] },
      { emoji: '🫡', keywords: ['salute', 'respect', 'yes sir', 'aye'] },
      { emoji: '🫰', keywords: ['hand with index and thumb crossed', 'money', 'snap'] },
    ],
  },
  {
    name: 'Hearts',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', keywords: ['red heart', 'love', 'like', 'valentine'] },
      { emoji: '🧡', keywords: ['orange heart', 'love'] },
      { emoji: '💛', keywords: ['yellow heart', 'love', 'friendship'] },
      { emoji: '💚', keywords: ['green heart', 'love', 'envy'] },
      { emoji: '💙', keywords: ['blue heart', 'love', 'trust'] },
      { emoji: '💜', keywords: ['purple heart', 'love'] },
      { emoji: '🖤', keywords: ['black heart', 'dark', 'love', 'goth'] },
      { emoji: '🤍', keywords: ['white heart', 'pure', 'love'] },
      { emoji: '🤎', keywords: ['brown heart', 'love'] },
      { emoji: '💔', keywords: ['broken heart', 'sad', 'heartbreak', 'breakup'] },
      { emoji: '❤️‍🔥', keywords: ['heart on fire', 'passion', 'burning love'] },
      { emoji: '💕', keywords: ['two hearts', 'love', 'pair'] },
      { emoji: '💞', keywords: ['revolving hearts', 'love', 'spinning'] },
      { emoji: '💓', keywords: ['beating heart', 'love', 'pulse', 'alive'] },
      { emoji: '💗', keywords: ['growing heart', 'love', 'expanding'] },
      { emoji: '💖', keywords: ['sparkling heart', 'love', 'sparkle', 'shiny'] },
      { emoji: '💘', keywords: ['cupid', 'arrow', 'love', 'valentine'] },
      { emoji: '💝', keywords: ['gift heart', 'ribbon', 'love', 'present'] },
      { emoji: '💟', keywords: ['heart decoration', 'love'] },
      { emoji: '♥️', keywords: ['heart suit', 'cards', 'love'] },
    ],
  },
  {
    name: 'Nature',
    icon: '🌿',
    emojis: [
      { emoji: '🐶', keywords: ['dog', 'puppy', 'pet', 'woof'] },
      { emoji: '🐱', keywords: ['cat', 'kitten', 'pet', 'meow'] },
      { emoji: '🐭', keywords: ['mouse', 'rodent', 'squeak'] },
      { emoji: '🐹', keywords: ['hamster', 'pet', 'cute', 'rodent'] },
      { emoji: '🐰', keywords: ['rabbit', 'bunny', 'pet', 'easter'] },
      { emoji: '🦊', keywords: ['fox', 'clever', 'animal'] },
      { emoji: '🐻', keywords: ['bear', 'animal', 'brown bear'] },
      { emoji: '🐼', keywords: ['panda', 'bear', 'cute', 'china'] },
      { emoji: '🐨', keywords: ['koala', 'animal', 'australia', 'cute'] },
      { emoji: '🐯', keywords: ['tiger', 'cat', 'wild', 'rawr'] },
      { emoji: '🦁', keywords: ['lion', 'king', 'wild', 'roar'] },
      { emoji: '🐮', keywords: ['cow', 'moo', 'farm', 'animal'] },
      { emoji: '🐷', keywords: ['pig', 'oink', 'farm', 'animal'] },
      { emoji: '🐸', keywords: ['frog', 'ribbit', 'toad', 'pepe'] },
      { emoji: '🐵', keywords: ['monkey', 'ape', 'animal', 'primate'] },
      { emoji: '🙈', keywords: ['see no evil', 'monkey', 'hide', 'blind', 'shy'] },
      { emoji: '🙉', keywords: ['hear no evil', 'monkey', 'deaf'] },
      { emoji: '🙊', keywords: ['speak no evil', 'monkey', 'mute', 'oops'] },
      { emoji: '🐔', keywords: ['chicken', 'bird', 'farm', 'hen'] },
      { emoji: '🐧', keywords: ['penguin', 'bird', 'cold', 'arctic', 'cute'] },
      { emoji: '🐦', keywords: ['bird', 'tweet', 'fly'] },
      { emoji: '🦆', keywords: ['duck', 'bird', 'quack', 'water'] },
      { emoji: '🦅', keywords: ['eagle', 'bird', 'america', 'freedom'] },
      { emoji: '🦉', keywords: ['owl', 'bird', 'wise', 'night'] },
      { emoji: '🐝', keywords: ['bee', 'honey', 'buzz', 'insect'] },
      { emoji: '🐛', keywords: ['bug', 'insect', 'caterpillar', 'worm'] },
      { emoji: '🦋', keywords: ['butterfly', 'insect', 'pretty', 'nature'] },
      { emoji: '🐌', keywords: ['snail', 'slow', 'shell'] },
      { emoji: '🐞', keywords: ['ladybug', 'insect', 'luck'] },
      { emoji: '🐜', keywords: ['ant', 'insect', 'bug', 'small'] },
      { emoji: '🪲', keywords: ['beetle', 'bug', 'insect'] },
      { emoji: '🌸', keywords: ['cherry blossom', 'flower', 'spring', 'pink', 'sakura'] },
      { emoji: '🌹', keywords: ['rose', 'flower', 'love', 'romantic', 'red'] },
      { emoji: '🌺', keywords: ['hibiscus', 'flower', 'tropical'] },
      { emoji: '🌻', keywords: ['sunflower', 'flower', 'sun', 'yellow'] },
      { emoji: '🌼', keywords: ['blossom', 'flower', 'daisy', 'yellow'] },
      { emoji: '🌷', keywords: ['tulip', 'flower', 'spring'] },
      { emoji: '🌱', keywords: ['seedling', 'plant', 'grow', 'sprout', 'new'] },
      { emoji: '🌲', keywords: ['evergreen', 'tree', 'pine', 'forest'] },
      { emoji: '🌳', keywords: ['tree', 'deciduous', 'forest', 'nature'] },
      { emoji: '🍀', keywords: ['four leaf clover', 'lucky', 'irish', 'luck'] },
      { emoji: '🍁', keywords: ['maple leaf', 'fall', 'autumn', 'canada'] },
      { emoji: '🍂', keywords: ['fallen leaf', 'autumn', 'fall'] },
      { emoji: '🍃', keywords: ['leaf', 'wind', 'blow', 'nature'] },
      { emoji: '🌍', keywords: ['earth', 'world', 'globe', 'planet'] },
      { emoji: '🌈', keywords: ['rainbow', 'colors', 'pride', 'weather'] },
      { emoji: '⭐', keywords: ['star', 'favorite', 'night', 'gold'] },
      { emoji: '🌙', keywords: ['moon', 'night', 'crescent', 'sleep'] },
      { emoji: '☀️', keywords: ['sun', 'sunny', 'bright', 'warm', 'weather'] },
      { emoji: '⛅', keywords: ['cloudy', 'cloud', 'sun', 'partly', 'weather'] },
      { emoji: '🌧', keywords: ['rain', 'cloud', 'weather', 'rainy'] },
      { emoji: '❄️', keywords: ['snowflake', 'snow', 'cold', 'winter', 'ice'] },
      { emoji: '🔥', keywords: ['fire', 'hot', 'flame', 'lit', 'burn'] },
      { emoji: '💧', keywords: ['water', 'drop', 'droplet', 'tear', 'sweat'] },
      { emoji: '🌊', keywords: ['wave', 'ocean', 'sea', 'water', 'surf'] },
    ],
  },
  {
    name: 'Food',
    icon: '🍔',
    emojis: [
      { emoji: '🍎', keywords: ['apple', 'red', 'fruit'] },
      { emoji: '🍐', keywords: ['pear', 'fruit', 'green'] },
      { emoji: '🍊', keywords: ['orange', 'tangerine', 'fruit', 'citrus'] },
      { emoji: '🍋', keywords: ['lemon', 'citrus', 'sour', 'yellow'] },
      { emoji: '🍌', keywords: ['banana', 'fruit', 'yellow'] },
      { emoji: '🍉', keywords: ['watermelon', 'fruit', 'summer'] },
      { emoji: '🍇', keywords: ['grapes', 'fruit', 'wine', 'purple'] },
      { emoji: '🍓', keywords: ['strawberry', 'fruit', 'berry', 'red'] },
      { emoji: '🫐', keywords: ['blueberries', 'berry', 'fruit'] },
      { emoji: '🍒', keywords: ['cherries', 'fruit', 'red'] },
      { emoji: '🍑', keywords: ['peach', 'fruit', 'butt'] },
      { emoji: '🥭', keywords: ['mango', 'fruit', 'tropical'] },
      { emoji: '🍍', keywords: ['pineapple', 'fruit', 'tropical'] },
      { emoji: '🥥', keywords: ['coconut', 'fruit', 'tropical'] },
      { emoji: '🥝', keywords: ['kiwi', 'fruit', 'green'] },
      { emoji: '🍅', keywords: ['tomato', 'vegetable', 'red'] },
      { emoji: '🥑', keywords: ['avocado', 'guac', 'green', 'toast'] },
      { emoji: '🌶', keywords: ['pepper', 'hot', 'chili', 'spicy'] },
      { emoji: '🥒', keywords: ['cucumber', 'vegetable', 'pickle'] },
      { emoji: '🥦', keywords: ['broccoli', 'vegetable', 'green'] },
      { emoji: '🧄', keywords: ['garlic', 'cooking', 'flavor'] },
      { emoji: '🥕', keywords: ['carrot', 'vegetable', 'orange'] },
      { emoji: '🌽', keywords: ['corn', 'maize', 'vegetable'] },
      { emoji: '🍞', keywords: ['bread', 'toast', 'loaf', 'bakery'] },
      { emoji: '🥐', keywords: ['croissant', 'pastry', 'french', 'bakery'] },
      { emoji: '🥖', keywords: ['baguette', 'bread', 'french'] },
      { emoji: '🥨', keywords: ['pretzel', 'snack', 'baked'] },
      { emoji: '🧀', keywords: ['cheese', 'dairy', 'wedge'] },
      { emoji: '🍖', keywords: ['meat', 'bone', 'leg'] },
      { emoji: '🍗', keywords: ['chicken leg', 'poultry', 'drumstick'] },
      { emoji: '🥩', keywords: ['steak', 'meat', 'beef', 'cut'] },
      { emoji: '🍔', keywords: ['burger', 'hamburger', 'cheeseburger', 'fast food'] },
      { emoji: '🍟', keywords: ['fries', 'french fries', 'chips', 'fast food'] },
      { emoji: '🍕', keywords: ['pizza', 'slice', 'pepperoni', 'italian'] },
      { emoji: '🌭', keywords: ['hot dog', 'sausage', 'frank'] },
      { emoji: '🥪', keywords: ['sandwich', 'bread', 'lunch'] },
      { emoji: '🌮', keywords: ['taco', 'mexican', 'tuesday'] },
      { emoji: '🌯', keywords: ['burrito', 'wrap', 'mexican'] },
      { emoji: '🥙', keywords: ['pita', 'falafel', 'stuffed'] },
      { emoji: '🍳', keywords: ['egg', 'cooking', 'fried egg', 'breakfast'] },
      { emoji: '🥘', keywords: ['paella', 'pan', 'stew', 'cooking'] },
      { emoji: '🍲', keywords: ['stew', 'pot', 'soup', 'hot'] },
      { emoji: '🍜', keywords: ['ramen', 'noodles', 'soup', 'steaming'] },
      { emoji: '🍝', keywords: ['spaghetti', 'pasta', 'italian', 'noodles'] },
      { emoji: '🍣', keywords: ['sushi', 'japanese', 'fish', 'rice'] },
      { emoji: '🍤', keywords: ['shrimp', 'prawn', 'seafood', 'tempura'] },
      { emoji: '🍦', keywords: ['ice cream', 'soft serve', 'dessert', 'cone'] },
      { emoji: '🍧', keywords: ['shaved ice', 'dessert', 'snow cone'] },
      { emoji: '🍨', keywords: ['ice cream', 'dessert', 'sundae'] },
      { emoji: '🍩', keywords: ['donut', 'doughnut', 'dessert', 'sprinkles'] },
      { emoji: '🍪', keywords: ['cookie', 'biscuit', 'dessert', 'chocolate chip'] },
      { emoji: '🎂', keywords: ['birthday cake', 'cake', 'party', 'celebration'] },
      { emoji: '🍰', keywords: ['cake', 'slice', 'shortcake', 'dessert'] },
      { emoji: '🧁', keywords: ['cupcake', 'muffin', 'dessert'] },
      { emoji: '🍫', keywords: ['chocolate', 'candy', 'sweet'] },
      { emoji: '🍬', keywords: ['candy', 'sweet', 'sugar'] },
      { emoji: '🍭', keywords: ['lollipop', 'candy', 'sweet', 'sugar'] },
      { emoji: '🍮', keywords: ['custard', 'pudding', 'flan', 'dessert'] },
      { emoji: '🍯', keywords: ['honey', 'pot', 'sweet', 'bee'] },
      { emoji: '☕', keywords: ['coffee', 'tea', 'hot', 'drink', 'cup', 'cafe'] },
      { emoji: '🍵', keywords: ['tea', 'green tea', 'cup', 'drink', 'hot'] },
      { emoji: '🍶', keywords: ['sake', 'rice wine', 'japanese', 'drink'] },
      { emoji: '🍷', keywords: ['wine', 'red wine', 'glass', 'drink', 'alcohol'] },
      { emoji: '🍸', keywords: ['cocktail', 'martini', 'drink', 'alcohol'] },
      { emoji: '🍹', keywords: ['tropical drink', 'cocktail', 'beach', 'alcohol'] },
      { emoji: '🍺', keywords: ['beer', 'drink', 'mug', 'alcohol', 'pint'] },
      { emoji: '🍻', keywords: ['beers', 'cheers', 'clink', 'drink', 'toast'] },
      { emoji: '🥂', keywords: ['champagne', 'cheers', 'toast', 'celebrate', 'sparkling'] },
      { emoji: '🥃', keywords: ['whiskey', 'tumbler', 'drink', 'alcohol', 'bourbon'] },
      { emoji: '🧋', keywords: ['boba', 'bubble tea', 'milk tea', 'drink'] },
      { emoji: '🥤', keywords: ['cup with straw', 'soda', 'juice', 'drink'] },
    ],
  },
  {
    name: 'Activities',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', keywords: ['soccer', 'football', 'ball', 'sport'] },
      { emoji: '🏀', keywords: ['basketball', 'ball', 'sport', 'nba'] },
      { emoji: '🏈', keywords: ['football', 'american', 'sport', 'nfl'] },
      { emoji: '⚾', keywords: ['baseball', 'ball', 'sport', 'mlb'] },
      { emoji: '🎾', keywords: ['tennis', 'ball', 'sport', 'racket'] },
      { emoji: '🏐', keywords: ['volleyball', 'ball', 'sport'] },
      { emoji: '🏉', keywords: ['rugby', 'ball', 'sport'] },
      { emoji: '🎱', keywords: ['pool', 'billiards', 'ball', '8 ball'] },
      { emoji: '🏓', keywords: ['ping pong', 'table tennis', 'paddle'] },
      { emoji: '🏸', keywords: ['badminton', 'shuttlecock', 'racket'] },
      { emoji: '🥊', keywords: ['boxing', 'glove', 'fight', 'punch'] },
      { emoji: '🎽', keywords: ['running shirt', 'sport', 'jersey'] },
      { emoji: '🛹', keywords: ['skateboard', 'skate', 'board'] },
      { emoji: '🎿', keywords: ['skiing', 'ski', 'snow', 'winter'] },
      { emoji: '🏆', keywords: ['trophy', 'winner', 'champion', 'award', 'cup'] },
      { emoji: '🥇', keywords: ['gold medal', 'first', 'winner', '1st'] },
      { emoji: '🥈', keywords: ['silver medal', 'second', '2nd'] },
      { emoji: '🥉', keywords: ['bronze medal', 'third', '3rd'] },
      { emoji: '🏅', keywords: ['medal', 'sports', 'award'] },
      { emoji: '🎖', keywords: ['military medal', 'honor', 'award'] },
      { emoji: '🎗', keywords: ['ribbon', 'awareness', 'reminder'] },
      { emoji: '🎫', keywords: ['ticket', 'admission', 'event', 'pass'] },
      { emoji: '🎪', keywords: ['circus', 'tent', 'carnival', 'show'] },
      { emoji: '🎭', keywords: ['theater', 'drama', 'performing arts', 'masks'] },
      { emoji: '🎨', keywords: ['art', 'paint', 'palette', 'creative', 'draw'] },
      { emoji: '🎬', keywords: ['movie', 'film', 'clapper', 'action', 'cinema'] },
      { emoji: '🎤', keywords: ['microphone', 'mic', 'sing', 'karaoke', 'music'] },
      { emoji: '🎧', keywords: ['headphones', 'music', 'listen', 'audio'] },
      { emoji: '🎼', keywords: ['music', 'score', 'notes', 'sheet'] },
      { emoji: '🎹', keywords: ['piano', 'keyboard', 'music', 'keys'] },
      { emoji: '🥁', keywords: ['drum', 'music', 'beat', 'percussion'] },
      { emoji: '🎷', keywords: ['saxophone', 'sax', 'music', 'jazz'] },
      { emoji: '🎺', keywords: ['trumpet', 'music', 'brass', 'horn'] },
      { emoji: '🎸', keywords: ['guitar', 'music', 'rock', 'electric'] },
      { emoji: '🎻', keywords: ['violin', 'music', 'classical', 'fiddle'] },
      { emoji: '🎲', keywords: ['dice', 'game', 'roll', 'chance', 'gamble'] },
      { emoji: '🎯', keywords: ['bullseye', 'target', 'dart', 'direct hit'] },
      { emoji: '🎳', keywords: ['bowling', 'pin', 'strike', 'sport'] },
      { emoji: '🎮', keywords: ['video game', 'controller', 'gaming', 'play'] },
      { emoji: '🧩', keywords: ['puzzle', 'piece', 'jigsaw', 'game'] },
      { emoji: '🎰', keywords: ['slot machine', 'gamble', 'casino', 'jackpot'] },
    ],
  },
  {
    name: 'Objects',
    icon: '💡',
    emojis: [
      { emoji: '⌚', keywords: ['watch', 'time', 'clock', 'wrist'] },
      { emoji: '📱', keywords: ['phone', 'mobile', 'iphone', 'cell', 'smartphone'] },
      { emoji: '💻', keywords: ['laptop', 'computer', 'pc', 'mac', 'coding'] },
      { emoji: '⌨', keywords: ['keyboard', 'type', 'computer', 'input'] },
      { emoji: '🖥', keywords: ['desktop', 'computer', 'monitor', 'screen'] },
      { emoji: '🖨', keywords: ['printer', 'paper', 'print'] },
      { emoji: '🖱', keywords: ['mouse', 'computer', 'click', 'cursor'] },
      { emoji: '💽', keywords: ['minidisc', 'disk', 'data', 'storage'] },
      { emoji: '💾', keywords: ['floppy disk', 'save', 'storage', 'retro'] },
      { emoji: '💿', keywords: ['cd', 'disc', 'dvd', 'music'] },
      { emoji: '📀', keywords: ['dvd', 'disc', 'movie', 'blu-ray'] },
      { emoji: '📷', keywords: ['camera', 'photo', 'picture', 'snap'] },
      { emoji: '📹', keywords: ['video camera', 'record', 'film'] },
      { emoji: '🎥', keywords: ['movie camera', 'film', 'cinema', 'record'] },
      { emoji: '📞', keywords: ['telephone', 'phone', 'call', 'receiver'] },
      { emoji: '📺', keywords: ['tv', 'television', 'screen', 'watch'] },
      { emoji: '📻', keywords: ['radio', 'broadcast', 'music', 'listen'] },
      { emoji: '🧭', keywords: ['compass', 'navigate', 'direction', 'north'] },
      { emoji: '⏰', keywords: ['alarm clock', 'time', 'wake up', 'morning'] },
      { emoji: '⌛', keywords: ['hourglass', 'time', 'sand', 'timer'] },
      { emoji: '📡', keywords: ['satellite', 'antenna', 'signal', 'broadcast'] },
      { emoji: '🔋', keywords: ['battery', 'power', 'charge', 'energy'] },
      { emoji: '🔌', keywords: ['plug', 'electric', 'power', 'charge'] },
      { emoji: '💡', keywords: ['light bulb', 'idea', 'bright', 'lamp'] },
      { emoji: '🔦', keywords: ['flashlight', 'torch', 'light', 'dark'] },
      { emoji: '🕯', keywords: ['candle', 'light', 'flame', 'romantic'] },
      { emoji: '🧯', keywords: ['fire extinguisher', 'safety', 'emergency'] },
      { emoji: '💸', keywords: ['money with wings', 'spending', 'flying money', 'expensive'] },
      { emoji: '💵', keywords: ['dollar', 'money', 'cash', 'bill'] },
      { emoji: '💰', keywords: ['money bag', 'rich', 'cash', 'dollar'] },
      { emoji: '💳', keywords: ['credit card', 'payment', 'buy', 'swipe'] },
      { emoji: '💎', keywords: ['gem', 'diamond', 'jewel', 'precious', 'bling'] },
      { emoji: '🔧', keywords: ['wrench', 'tool', 'fix', 'repair'] },
      { emoji: '🔩', keywords: ['nut and bolt', 'tool', 'hardware'] },
      { emoji: '⚙', keywords: ['gear', 'settings', 'cog', 'mechanical'] },
      { emoji: '🔫', keywords: ['water gun', 'squirt', 'pistol', 'weapon'] },
      { emoji: '💣', keywords: ['bomb', 'explosive', 'boom'] },
      { emoji: '🔪', keywords: ['knife', 'cut', 'kitchen', 'blade'] },
      { emoji: '🛡', keywords: ['shield', 'protect', 'defense', 'guard'] },
      { emoji: '🔑', keywords: ['key', 'lock', 'unlock', 'password'] },
      { emoji: '🗝', keywords: ['old key', 'skeleton key', 'lock', 'antique'] },
      { emoji: '🚪', keywords: ['door', 'entrance', 'exit'] },
      { emoji: '🛋', keywords: ['couch', 'sofa', 'relax', 'furniture'] },
      { emoji: '🛏', keywords: ['bed', 'sleep', 'rest', 'furniture'] },
      { emoji: '📝', keywords: ['memo', 'note', 'write', 'pencil', 'paper'] },
      { emoji: '💼', keywords: ['briefcase', 'business', 'work', 'office'] },
      { emoji: '📁', keywords: ['folder', 'file', 'directory', 'organize'] },
      { emoji: '📅', keywords: ['calendar', 'date', 'schedule', 'event'] },
      { emoji: '📊', keywords: ['chart', 'graph', 'bar chart', 'stats', 'data'] },
      { emoji: '📌', keywords: ['pushpin', 'pin', 'location', 'mark'] },
      { emoji: '📎', keywords: ['paperclip', 'clip', 'attach'] },
      { emoji: '✂', keywords: ['scissors', 'cut', 'trim'] },
      { emoji: '🔒', keywords: ['lock', 'locked', 'secure', 'private'] },
      { emoji: '🔓', keywords: ['unlock', 'unlocked', 'open', 'access'] },
    ],
  },
  {
    name: 'Symbols',
    icon: '💯',
    emojis: [
      { emoji: '💯', keywords: ['hundred', 'perfect', 'score', '100', 'points'] },
      { emoji: '💢', keywords: ['anger', 'angry', 'symbol', 'mad'] },
      { emoji: '💥', keywords: ['boom', 'collision', 'explosion', 'bang', 'crash'] },
      { emoji: '💫', keywords: ['dizzy', 'star', 'sparkle', 'shooting star'] },
      { emoji: '💦', keywords: ['sweat', 'splash', 'water', 'droplets'] },
      { emoji: '💨', keywords: ['dash', 'wind', 'fast', 'running', 'speed'] },
      { emoji: '🕳', keywords: ['hole', 'void', 'empty'] },
      { emoji: '💬', keywords: ['speech bubble', 'comment', 'message', 'talk', 'chat'] },
      { emoji: '👁‍🗨', keywords: ['eye in speech bubble', 'witness'] },
      { emoji: '💭', keywords: ['thought bubble', 'thinking', 'dream'] },
      { emoji: '💤', keywords: ['zzz', 'sleep', 'snore', 'tired'] },
      { emoji: '🔔', keywords: ['bell', 'notification', 'alert', 'ring'] },
      { emoji: '🔕', keywords: ['no bell', 'mute', 'silent', 'quiet'] },
      { emoji: '🎵', keywords: ['music', 'note', 'melody', 'song'] },
      { emoji: '🎶', keywords: ['music', 'notes', 'singing', 'melody'] },
      { emoji: '✅', keywords: ['check', 'done', 'yes', 'complete', 'green'] },
      { emoji: '❌', keywords: ['cross', 'no', 'wrong', 'delete', 'cancel'] },
      { emoji: '❓', keywords: ['question', 'what', 'confused', 'help'] },
      { emoji: '❗', keywords: ['exclamation', 'important', 'warning', 'alert'] },
      { emoji: '‼', keywords: ['double exclamation', 'bangbang', 'urgent'] },
      { emoji: '⁉', keywords: ['exclamation question', 'what', 'surprise'] },
      { emoji: '🔅', keywords: ['low brightness', 'dim', 'dark'] },
      { emoji: '🔆', keywords: ['high brightness', 'bright', 'light'] },
      { emoji: '⚠️', keywords: ['warning', 'caution', 'alert', 'danger'] },
      { emoji: '🚫', keywords: ['no entry', 'prohibited', 'forbidden', 'stop', 'ban'] },
      { emoji: '♻️', keywords: ['recycle', 'environment', 'green', 'reuse'] },
      { emoji: '✨', keywords: ['sparkles', 'stars', 'shine', 'magic', 'new', 'clean'] },
      { emoji: '🎉', keywords: ['party', 'tada', 'celebration', 'confetti', 'hooray'] },
      { emoji: '🎊', keywords: ['confetti ball', 'party', 'celebration'] },
      { emoji: '🏳️‍🌈', keywords: ['rainbow flag', 'pride', 'lgbtq', 'gay'] },
      { emoji: '🏴‍☠️', keywords: ['pirate flag', 'pirate', 'skull', 'jolly roger'] },
      { emoji: '⚡', keywords: ['lightning', 'zap', 'electric', 'bolt', 'thunder', 'fast'] },
      { emoji: '🌟', keywords: ['glowing star', 'shine', 'sparkle', 'awesome'] },
      { emoji: '🔥', keywords: ['fire', 'hot', 'flame', 'lit', 'burn'] },
      { emoji: '👀', keywords: ['eyes', 'look', 'see', 'watch', 'stare'] },
      { emoji: '🫡', keywords: ['salute', 'respect', 'yes sir', 'aye'] },
      { emoji: '🫶', keywords: ['heart hands', 'love', 'care'] },
    ],
  },
];

export const EMOJI_ALIASES: Record<string, string[]> = Object.fromEntries(
  EMOJI_CATEGORIES.flatMap(c => c.emojis).map(e => [e.emoji, e.keywords])
);

export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap(c => c.emojis.map(e => e.emoji));
